version: "3"

services:
    frontend:
        build:
            context: ./ZimmerMaticFrontend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"

    backend:
        build:
            context: ./ZimmerMaticBackend
            dockerfile: Dockerfile
        ports:
            - "3443:3443"
            - "8000:8000"